#pragma once

// Generated by tools/generate_dcs_ids.ps1 from DcsIds/CommandIds.json.
// Do not edit this file directly.
namespace DcsIds
{
namespace CockpitParams
{
static const char* const TemperatureC = "FM_TEMPERATURE_C";
static const char* const MaxPowerSwitch = "FM_MAXPOWER_SWITCH";
static const char* const MaxPowerReady = "FM_MAXPOWER_READY";
static const char* const ApMasterEngaged = "AP_MASTER_ENGAGED";
static const char* const ApPitchCommand = "AP_PITCH_CMD";
static const char* const ApRollCommand = "AP_ROLL_CMD";
static const char* const ApThrottleCommand = "AP_THROTTLE_CMD";
static const char* const ApBypassActive = "AP_BYPASS_ACTIVE";
static const char* const ApAutoThrottleEngaged = "AP_AT_ENGAGED";
}
}
