#pragma once

// Generated by tools/generate_dcs_ids.ps1 from DcsIds/CommandIds.json.
// Do not edit this file directly.
namespace DcsIds
{
namespace Commands
{
static constexpr int FBWCatToggle = 3007;
static constexpr int FBWCat1 = 3008;
static constexpr int FBWCat3 = 3009;
static constexpr int AirBrakesAuto = 3010;
static constexpr int GearAuto = 3011;
static constexpr int FlapsAuto = 3012;
static constexpr int NoseTurnUp = 3013;
static constexpr int NoseTurnAuto = 3014;
static constexpr int NoseTurnDown = 3015;
static constexpr int AirBrakesUp = 3016;
static constexpr int AirBrakesDown = 3017;
static constexpr int GearHandleUp = 3018;
static constexpr int GearHandleDown = 3019;
static constexpr int FlapsUpCmd = 3020;
static constexpr int FlapsDownCmd = 3021;
static constexpr int NoseTurnToggle = 3022;
static constexpr int WheelBrakeAxis = 3023;
static constexpr int WheelBrakeAxisLeft = 3024;
static constexpr int WheelBrakeAxisRight = 3025;
static constexpr int FBWGLimiterOverride = 3026;
static constexpr int FBWGLimiterOverrideToggle = 3027;
static constexpr int TriggerFirstStage = 3030;
static constexpr int CMSForward = 3031;
static constexpr int CMSAft = 3032;
static constexpr int CMSLeft = 3033;
static constexpr int CMSRight = 3034;
static constexpr int CMSPress = 3035;
static constexpr int TriggerSecondStage = 3036;
static constexpr int MasterArmOn = 3040;
static constexpr int MasterArmOff = 3041;
static constexpr int MasterArmSim = 3042;
static constexpr int DogfightSwitch = 3043;
static constexpr int MissileUncage = 3044;
static constexpr int WeaponRelease = 3045;
static constexpr int TargetLock = 3046;
static constexpr int TMSUp = 3046;
static constexpr int TMSDown = 3047;
static constexpr int TMSLeft = 3048;
static constexpr int TMSRight = 3049;
static constexpr int NavMode = 3050;
static constexpr int MissileOverride = 3051;
static constexpr int SoundTestCycle = 3052;
static constexpr int APMasterToggle = 3100;
static constexpr int APMasterOn = 3101;
static constexpr int APMasterOff = 3102;
static constexpr int APBypass = 3103;
static constexpr int APVertPitchHold = 3110;
static constexpr int APVertVSHold = 3111;
static constexpr int APVertAltHold = 3112;
static constexpr int APVertIncrease = 3113;
static constexpr int APVertDecrease = 3114;
static constexpr int APLatHeadingHold = 3120;
static constexpr int APLatHeadingSelect = 3121;
static constexpr int APLatNavTrack = 3122;
static constexpr int APLatIncrease = 3123;
static constexpr int APLatDecrease = 3124;
static constexpr int APAutoThrottleToggle = 3130;
static constexpr int APAutoThrottleOn = 3131;
static constexpr int APAutoThrottleOff = 3132;
static constexpr int APSpeedIncrease = 3133;
static constexpr int APSpeedDecrease = 3134;
static constexpr int EngineThrustCutTestToggle = 3135;
static constexpr int APMaxpowerToggle = 3135;
static constexpr int EngineThrustCutTestEnable = 3136;
static constexpr int EngineThrustCutTestDisable = 3137;
}
}
