#pragma once

// Generated by tools/generate_dcs_ids.ps1 from DcsIds/CommandIds.json.
// Do not edit this file directly.
namespace DcsIds
{
namespace Commands
{
static constexpr int FBWCatToggle = 3007;
static constexpr int FBWCat1 = 3008;
static constexpr int FBWCat3 = 3009;
static constexpr int AirBrakesAuto = 3010;
static constexpr int GearAuto = 3011;
static constexpr int FlapsAuto = 3012;
static constexpr int NoseTurnUp = 3013;
static constexpr int NoseTurnAuto = 3014;
static constexpr int NoseTurnDown = 3015;
static constexpr int AirBrakesUp = 3016;
static constexpr int AirBrakesDown = 3017;
static constexpr int GearHandleUp = 3018;
static constexpr int GearHandleDown = 3019;
static constexpr int FlapsUpCmd = 3020;
static constexpr int FlapsDownCmd = 3021;
static constexpr int NoseTurnToggle = 3022;
static constexpr int WheelBrakeAxis = 3023;
static constexpr int WheelBrakeAxisLeft = 3024;
static constexpr int WheelBrakeAxisRight = 3025;
static constexpr int FBWGLimiterOverride = 3026;
static constexpr int FBWGLimiterOverrideToggle = 3027;
static constexpr int TriggerFirstStage = 3030;
static constexpr int CMSForward = 3031;
static constexpr int CMSAft = 3032;
static constexpr int CMSLeft = 3033;
static constexpr int CMSRight = 3034;
static constexpr int CMSPress = 3035;
static constexpr int TriggerSecondStage = 3036;
static constexpr int MasterArmOn = 3040;
static constexpr int MasterArmOff = 3041;
static constexpr int MasterArmSim = 3042;
static constexpr int DogfightSwitch = 3043;
static constexpr int MissileUncage = 3044;
static constexpr int WeaponRelease = 3045;
static constexpr int TMSUp = 3046;
static constexpr int TMSDown = 3047;
static constexpr int TMSLeft = 3048;
static constexpr int TMSRight = 3049;
static constexpr int NavMode = 3050;
static constexpr int MissileOverride = 3051;
static constexpr int SoundTestCycle = 3052;
static constexpr int APMasterToggle = 3100;
static constexpr int APMasterOn = 3101;
static constexpr int APMasterOff = 3102;
static constexpr int APBypass = 3103;
static constexpr int APVertPitchHold = 3110;
static constexpr int APVertVSHold = 3111;
static constexpr int APVertAltHold = 3112;
static constexpr int APVertIncrease = 3113;
static constexpr int APVertDecrease = 3114;
static constexpr int APLatHeadingHold = 3120;
static constexpr int APLatHeadingSelect = 3121;
static constexpr int APLatNavTrack = 3122;
static constexpr int APLatIncrease = 3123;
static constexpr int APLatDecrease = 3124;
static constexpr int APAutoThrottleToggle = 3130;
static constexpr int APAutoThrottleOn = 3131;
static constexpr int APAutoThrottleOff = 3132;
static constexpr int APSpeedIncrease = 3133;
static constexpr int APSpeedDecrease = 3134;
static constexpr int EngineThrustCutTestToggle = 3135;
static constexpr int EngineThrustCutTestEnable = 3136;
static constexpr int EngineThrustCutTestDisable = 3137;
}

namespace DcsCommands
{
static constexpr int iCommandPlaneFire = 84;
static constexpr int iCommandPlaneFireOff = 85;
static constexpr int iCommandPlaneRadarOnOff = 86;
static constexpr int iCommandPlaneEOSOnOff = 87;
static constexpr int iCommandPlaneChangeLock = 100;
static constexpr int iCommandPlaneChangeWeapon = 101;
static constexpr int iCommandPlaneModeBVR = 106;
static constexpr int iCommandPlaneModeVS = 107;
static constexpr int iCommandPlaneModeBore = 108;
static constexpr int iCommandPlaneModeHelmet = 109;
static constexpr int iCommandPlaneModeFI0 = 110;
static constexpr int iCommandPlaneModeCannon = 113;
static constexpr int iCommandPlaneDropSnarOnce = 176;
static constexpr int iCommandPlaneLaunchPermissionOverride = 349;
static constexpr int iCommandPlanePickleOn = 350;
static constexpr int iCommandPlanePickleOff = 351;
static constexpr int iCommandPlaneDropFlareOnce = 357;
static constexpr int iCommandPlaneDropChaffOnce = 358;
static constexpr int iCommandPlaneLockOnStart = 509;
static constexpr int iCommandPlaneLockOnFinish = 510;
static constexpr int iCommandPlaneDropSnarOnceOff = 536;
static constexpr int iCommandPlane_ShowControls = 851;
static constexpr int iCommandViewPauseOnOff = 1609;
static constexpr int iCommandPlaneChangeLockUp = 1627;
static constexpr int iCommandPlaneFeedbackTrimmer = 2035;
static constexpr int iServiceInformAboutUserHAngle = 2142;
static constexpr int iServiceInformAboutUserVAngle = 2143;
}

namespace CommandRouting
{
enum class Route
{
    Efm,
    Cockpit
};

struct Entry
{
    int id;
    Route route;
};

static constexpr Entry CustomCommands[] = {
    { Commands::FBWCatToggle, Route::Efm },
    { Commands::FBWCat1, Route::Efm },
    { Commands::FBWCat3, Route::Efm },
    { Commands::AirBrakesAuto, Route::Efm },
    { Commands::GearAuto, Route::Efm },
    { Commands::FlapsAuto, Route::Efm },
    { Commands::NoseTurnUp, Route::Efm },
    { Commands::NoseTurnAuto, Route::Efm },
    { Commands::NoseTurnDown, Route::Efm },
    { Commands::AirBrakesUp, Route::Efm },
    { Commands::AirBrakesDown, Route::Efm },
    { Commands::GearHandleUp, Route::Efm },
    { Commands::GearHandleDown, Route::Efm },
    { Commands::FlapsUpCmd, Route::Efm },
    { Commands::FlapsDownCmd, Route::Efm },
    { Commands::NoseTurnToggle, Route::Efm },
    { Commands::WheelBrakeAxis, Route::Efm },
    { Commands::WheelBrakeAxisLeft, Route::Efm },
    { Commands::WheelBrakeAxisRight, Route::Efm },
    { Commands::FBWGLimiterOverride, Route::Efm },
    { Commands::FBWGLimiterOverrideToggle, Route::Efm },
    { Commands::TriggerFirstStage, Route::Cockpit },
    { Commands::CMSForward, Route::Cockpit },
    { Commands::CMSAft, Route::Cockpit },
    { Commands::CMSLeft, Route::Cockpit },
    { Commands::CMSRight, Route::Cockpit },
    { Commands::CMSPress, Route::Cockpit },
    { Commands::TriggerSecondStage, Route::Cockpit },
    { Commands::MasterArmOn, Route::Cockpit },
    { Commands::MasterArmOff, Route::Cockpit },
    { Commands::MasterArmSim, Route::Cockpit },
    { Commands::DogfightSwitch, Route::Cockpit },
    { Commands::MissileUncage, Route::Cockpit },
    { Commands::WeaponRelease, Route::Cockpit },
    { Commands::TMSUp, Route::Cockpit },
    { Commands::TMSDown, Route::Cockpit },
    { Commands::TMSLeft, Route::Cockpit },
    { Commands::TMSRight, Route::Cockpit },
    { Commands::NavMode, Route::Cockpit },
    { Commands::MissileOverride, Route::Cockpit },
    { Commands::SoundTestCycle, Route::Cockpit },
    { Commands::APMasterToggle, Route::Cockpit },
    { Commands::APMasterOn, Route::Cockpit },
    { Commands::APMasterOff, Route::Cockpit },
    { Commands::APBypass, Route::Cockpit },
    { Commands::APVertPitchHold, Route::Cockpit },
    { Commands::APVertVSHold, Route::Cockpit },
    { Commands::APVertAltHold, Route::Cockpit },
    { Commands::APVertIncrease, Route::Cockpit },
    { Commands::APVertDecrease, Route::Cockpit },
    { Commands::APLatHeadingHold, Route::Cockpit },
    { Commands::APLatHeadingSelect, Route::Cockpit },
    { Commands::APLatNavTrack, Route::Cockpit },
    { Commands::APLatIncrease, Route::Cockpit },
    { Commands::APLatDecrease, Route::Cockpit },
    { Commands::APAutoThrottleToggle, Route::Cockpit },
    { Commands::APAutoThrottleOn, Route::Cockpit },
    { Commands::APAutoThrottleOff, Route::Cockpit },
    { Commands::APSpeedIncrease, Route::Cockpit },
    { Commands::APSpeedDecrease, Route::Cockpit },
    { Commands::EngineThrustCutTestToggle, Route::Cockpit },
    { Commands::EngineThrustCutTestEnable, Route::Cockpit },
    { Commands::EngineThrustCutTestDisable, Route::Cockpit },
};

static constexpr int IgnoredDcsCommands[] = {
    DcsCommands::iCommandPlaneFire,
    DcsCommands::iCommandPlaneFireOff,
    DcsCommands::iCommandPlaneRadarOnOff,
    DcsCommands::iCommandPlaneEOSOnOff,
    DcsCommands::iCommandPlaneChangeLock,
    DcsCommands::iCommandPlaneChangeWeapon,
    DcsCommands::iCommandPlaneModeBVR,
    DcsCommands::iCommandPlaneModeVS,
    DcsCommands::iCommandPlaneModeBore,
    DcsCommands::iCommandPlaneModeHelmet,
    DcsCommands::iCommandPlaneModeFI0,
    DcsCommands::iCommandPlaneModeCannon,
    DcsCommands::iCommandPlaneDropSnarOnce,
    DcsCommands::iCommandPlaneLaunchPermissionOverride,
    DcsCommands::iCommandPlanePickleOn,
    DcsCommands::iCommandPlanePickleOff,
    DcsCommands::iCommandPlaneDropFlareOnce,
    DcsCommands::iCommandPlaneDropChaffOnce,
    DcsCommands::iCommandPlaneLockOnStart,
    DcsCommands::iCommandPlaneLockOnFinish,
    DcsCommands::iCommandPlaneDropSnarOnceOff,
    DcsCommands::iCommandPlane_ShowControls,
    DcsCommands::iCommandViewPauseOnOff,
    DcsCommands::iCommandPlaneChangeLockUp,
    DcsCommands::iCommandPlaneFeedbackTrimmer,
    DcsCommands::iServiceInformAboutUserHAngle,
    DcsCommands::iServiceInformAboutUserVAngle,
};
}
}
