local res = external_profile("Config/Input/Aircrafts/common_keyboard_binding.lua")
local cscripts = folder .. "../../../Cockpit/Scripts/"
dofile(cscripts .. "devices.lua")
dofile(cscripts .. "command_defs.lua")

join(res.keyCommands,
    {
        { combos = defaultDeviceAssignmentFor("pitch_up"),          down = iCommandPlaneUpStart,                   up = iCommandPlaneUpStop,                   name = _('Aircraft Pitch Down'),                                            category = { _('Flight Control') } },
        { combos = defaultDeviceAssignmentFor("pitch_down"),        down = iCommandPlaneDownStart,                 up = iCommandPlaneDownStop,                 name = _('Aircraft Pitch Up'),                                              category = { _('Flight Control') } },

        { combos = defaultDeviceAssignmentFor("roll_left"),         down = iCommandPlaneLeftStart,                 up = iCommandPlaneLeftStop,                 name = _('Aircraft Bank Left'),                                             category = { _('Flight Control') } },
        { combos = defaultDeviceAssignmentFor("roll_right"),        down = iCommandPlaneRightStart,                up = iCommandPlaneRightStop,                name = _('Aircraft Bank Right'),                                            category = { _('Flight Control') } },

        { combos = defaultDeviceAssignmentFor("rudder_left"),       down = iCommandPlaneLeftRudderStart,           up = iCommandPlaneLeftRudderStop,           name = _('Aircraft Rudder Left'),                                           category = { _('Flight Control') } },
        { combos = defaultDeviceAssignmentFor("rudder_right"),      down = iCommandPlaneRightRudderStart,          up = iCommandPlaneRightRudderStop,          name = _('Aircraft Rudder Right'),                                          category = { _('Flight Control') } },

        { combos = defaultDeviceAssignmentFor("thrust_up"),         pressed = iCommandThrottleIncrease,            up = iCommandThrottleStop,                  name = _('Throttle Smoothly - Increase'),                                   category = { _('Throttle Quadrant'), _('Flight Control') } },
        { combos = defaultDeviceAssignmentFor("thrust_down"),       pressed = iCommandThrottleDecrease,            up = iCommandThrottleStop,                  name = _('Throttle Smoothly - Decrease'),                                   category = { _('Throttle Quadrant'), _('Flight Control') } },
        { combos = { { key = 'PageUp' } },                          pressed = iCommandThrottleIncrease,            up = iCommandThrottleStop,                  name = _('Throttle Smoothly - Increase'),   category = { _('Throttle Quadrant'), _('Flight Control') } },
        { combos = { { key = 'PageDown' } },                        pressed = iCommandThrottleDecrease,            up = iCommandThrottleStop,                  name = _('Throttle Smoothly - Decrease'),   category = { _('Throttle Quadrant'), _('Flight Control') } },
        { combos = { { key = 'PageUp', reformers = { 'RCtrl' } } }, down = iCommandThrottleIncrease,               name = _('Throttle Step - Increase'),       category = { _('Throttle Quadrant'), _('Flight Control') } },
        { combos = { { key = 'PageDown', reformers = { 'RCtrl' } } },down = iCommandThrottleDecrease,               name = _('Throttle Step - Decrease'),       category = { _('Throttle Quadrant'), _('Flight Control') } },

        { combos = defaultDeviceAssignmentFor("wheel_brake"),       down = iCommandPlaneWheelBrakeOn,              up = iCommandPlaneWheelBrakeOff,            name = _('Wheel Brake - ON/OFF'),                                           category = { _('Systems') } },
        { combos = { { key = 'W', reformers = { 'LCtrl' } } },      down = iCommandPlaneWheelBrakeLeftOn,          up = iCommandPlaneWheelBrakeLeftOff,        name = _('Wheel Brake Left - ON/OFF'),                                      category = { _('Systems') } },
        { combos = { { key = 'W', reformers = { 'LAlt' } } },       down = iCommandPlaneWheelBrakeRightOn,         up = iCommandPlaneWheelBrakeRightOff,       name = _('Wheel Brake Right - ON/OFF'),                                     category = { _('Systems') } },

        { combos = defaultDeviceAssignmentFor("plane_gear"),        down = iCommandPlaneGear,                      name = _('LG Handle - UP/DN'),              category = { _('Left Auxiliary Console') } },
        { combos = { { key = 'G', reformers = { 'LCtrl' } } },      down = iCommandPlaneGearUp,                    name = _('LG Handle - UP'),                 category = { _('Left Auxiliary Console') } },
        { combos = { { key = 'G', reformers = { 'LShift' } } },     down = iCommandPlaneGearDown,                  name = _('LG Handle - DN'),                 category = { _('Left Auxiliary Console') } },

        { combos = { { key = 'F' } },                               down = iCommandPlaneFlaps,                     name = _('Flap Handle - UP/DOWN'),          category = { _('Throttle Panel'), _('Flight Control') } },
        { combos = { { key = 'F', reformers = { 'LCtrl' } } },      down = iCommandPlaneFlapsOn,                   name = _('Flap Handle - DOWN'),             category = { _('Throttle Panel'), _('Flight Control') } },
        { combos = { { key = 'F', reformers = { 'LShift' } } },     down = iCommandPlaneFlapsOff,                  name = _('Flap Handle - UP'),               category = { _('Throttle Panel'), _('Flight Control') } },

        { combos = { { key = 'B' } },                               down = iCommandPlaneAirBrake,                  name = _('Speedbrake Switch - OPEN/CLOSE'), category = { _('Throttle Panel'), _('Throttle Grip'), _('Flight Control') } },
        { combos = { { key = 'B', reformers = { 'RCtrl' } } },      down = 3016,                                   name = _('Speedbrake 3-Pos - Close'),       category = { _('Throttle Panel'), _('Throttle Grip'), _('Flight Control') } },
        { combos = { { key = 'B', reformers = { 'RAlt' } } },       down = 3010,                                   name = _('Speedbrake 3-Pos - Hold'),        category = { _('Throttle Panel'), _('Throttle Grip'), _('Flight Control') } },
        { combos = { { key = 'B', reformers = { 'RShift' } } },     down = 3017,                                   name = _('Speedbrake 3-Pos - Extend'),      category = { _('Throttle Panel'), _('Throttle Grip'), _('Flight Control') } },

        { combos = { { key = 'F', reformers = { 'RCtrl' } } },      down = 3020,                                   name = _('Flap 3-Pos - UP'),                category = { _('Throttle Panel'), _('Flight Control') } },
        { combos = { { key = 'F', reformers = { 'RAlt' } } },       down = 3012,                                   name = _('Flap 3-Pos - AUTO'),              category = { _('Throttle Panel'), _('Flight Control') } },
        { combos = { { key = 'F', reformers = { 'RShift' } } },     down = 3021,                                   name = _('Flap 3-Pos - DOWN'),              category = { _('Throttle Panel'), _('Flight Control') } },

        { combos = { { key = 'N' } },                               down = 3022,                                   name = _('Nose Turn Switch - TOGGLE'),      category = { _('Systems') } },

        { combos = { { key = 'Space', reformers = { 'LAlt' } } },   down = device_commands.TriggerFirstStage,      up = device_commands.TriggerFirstStage,     cockpit_device_id = devices.CMS,                                            value_down = 1.0,                                          value_up = 0.0, name = _('HOTAS Trigger - First Stage'),                         category = { _('Weapons') } },
        { combos = { { key = 'Space' } },                           down = device_commands.TriggerSecondStage,     up = device_commands.TriggerSecondStage,    cockpit_device_id = devices.CMS,                                            value_down = 1.0,                                          value_up = 0.0, name = _('HOTAS Trigger - Second Stage (Gun Fire)'),       category = { _('Weapons') } },

        { combos = { { key = 'M', reformers = { 'RCtrl' } } },      down = device_commands.MasterArmOn,            up = device_commands.MasterArmOn,           cockpit_device_id = devices.CMS,                                            value_down = 1.0,                                          value_up = 0.0, name = _('Master Arm - ON (Momentary)'),                   category = { _('Weapons') } },
        { combos = { { key = 'M', reformers = { 'RShift' } } },     down = device_commands.MasterArmOff,           up = device_commands.MasterArmOff,          cockpit_device_id = devices.CMS,                                            value_down = 1.0,                                          value_up = 0.0, name = _('Master Arm - OFF (Momentary)'),                  category = { _('Weapons') } },
        { combos = { { key = 'M', reformers = { 'RAlt' } } },       down = device_commands.MasterArmSim,           up = device_commands.MasterArmSim,          cockpit_device_id = devices.CMS,                                            value_down = 1.0,                                          value_up = 0.0, name = _('Master Arm - SIM (Momentary)'),                  category = { _('Weapons') } },
        { combos = { { key = 'T', reformers = { 'RShift' } } },     down = device_commands.SoundTestCycle,         up = device_commands.SoundTestCycle,        cockpit_device_id = devices.AAM_AUDIO,                                      value_down = 1.0,                                          value_up = 0.0, name = _('Audio Test - Next Sound'),                       category = { _('Systems') } },
        { combos = { { key = '1' } },                               down = device_commands.NavMode,                up = device_commands.NavMode,               cockpit_device_id = devices.CMS,                                            value_down = 1.0,                                          value_up = 0.0, name = _('Fire Control Mode - NAV'),                       category = { _('Weapons') } },
        { combos = { { key = 'D', reformers = { 'RCtrl' } } },      down = device_commands.DogfightSwitch,         up = device_commands.DogfightSwitch,        cockpit_device_id = devices.CMS,                                            value_down = 1.0,                                          value_up = 0.0, name = _('Fire Control Mode - DGFT'),                      category = { _('Weapons') } },
        { combos = { { key = '4' } },                               down = device_commands.MissileOverride,        up = device_commands.MissileOverride,       cockpit_device_id = devices.CMS,                                            value_down = 1.0,                                          value_up = 0.0, name = _('Fire Control Mode - MSL OVRD'),                  category = { _('Weapons') } },
        { combos = { { key = 'M', reformers = { 'RAlt', 'RShift' } } }, down = device_commands.MissileUncage,       up = device_commands.MissileUncage,         cockpit_device_id = devices.CMS,                                            value_down = 1.0,                                          value_up = 0.0, name = _('Missile Uncage (Hold)'),                         category = { _('Weapons') } },
        { down = device_commands.WeaponRelease,                      up = device_commands.WeaponRelease,            cockpit_device_id = devices.CMS,                                            value_down = 1.0,                                          value_up = 0.0, name = _('Weapon Release (AAM, Uncage-Gated)'),            category = { _('Weapons') } },
        { combos = { { key = '2' } },                               down = iCommandPlaneModeBVR,                   name = _('Air-to-Air Mode - BVR (Direct)'),                                  category = { _('Modes') } },
        { combos = { { key = '3' } },                               down = iCommandPlaneModeBore,                  name = _('Air-to-Air Mode - Bore (Direct)'),                                 category = { _('Modes') } },
        { combos = { { key = '5' } },                               down = iCommandPlaneModeHelmet,                name = _('Air-to-Air Mode - Helmet (Direct)'),                               category = { _('Modes') } },
        { combos = { { key = '6' } },                               down = iCommandPlaneModeFI0,                   name = _('Air-to-Air Mode - FI0 (Direct)'),                                  category = { _('Modes') } },
        { combos = { { key = 'O' } },                               down = iCommandPlaneEOSOnOff,                  name = _('Electro-Optical System On/Off (IRST Test)'),                       category = { _('Sensors') } },
        { combos = { { key = 'Tab' } },                             down = iCommandPlaneChangeWeapon,              name = _('Weapon Change - Direct'),                                          category = { _('Weapons') } },
        { combos = { { key = 'Enter' } },                           down = device_commands.TMSUp,                  up = device_commands.TMSUp,                 cockpit_device_id = devices.CMS,                                            value_down = 1.0,                                          value_up = 0.0, name = _('HOTAS TMS - Up'),                                 category = { _('Sensors') } },
        { combos = { { key = 'Backspace' } },                       down = device_commands.TMSDown,                up = device_commands.TMSDown,               cockpit_device_id = devices.CMS,                                            value_down = 1.0,                                          value_up = 0.0, name = _('HOTAS TMS - Down'),                               category = { _('Sensors') } },
        { combos = { { key = '[' } },                               down = device_commands.TMSLeft,                up = device_commands.TMSLeft,               cockpit_device_id = devices.CMS,                                            value_down = 1.0,                                          value_up = 0.0, name = _('HOTAS TMS - Left'),                               category = { _('Sensors') } },
        { combos = { { key = ']' } },                               down = device_commands.TMSRight,               up = device_commands.TMSRight,              cockpit_device_id = devices.CMS,                                            value_down = 1.0,                                          value_up = 0.0, name = _('HOTAS TMS - Right'),                              category = { _('Sensors') } },

        { combos = { { key = 'Delete', reformers = { 'RAlt' } } }, down = device_commands.CMSForward,             up = device_commands.CMSForward,            cockpit_device_id = devices.CMS,                                            value_down = 1.0,                                          value_up = 0.0, name = _('HOTAS CMS - Forward (10x Flare + Chaff / 1s)'), category = { _('Countermeasures') }, features = { 'Countermeasures' } },
        { combos = { { key = 'Home', reformers = { 'RAlt' } } },   down = device_commands.CMSAft,                 up = device_commands.CMSAft,                cockpit_device_id = devices.CMS,                                            value_down = 1.0,                                          value_up = 0.0, name = _('HOTAS CMS - Aft (7x Chaff / 0.5s)'),            category = { _('Countermeasures') }, features = { 'Countermeasures' } },
        { combos = { { key = 'Insert', reformers = { 'RAlt' } } }, down = device_commands.CMSLeft,                up = device_commands.CMSLeft,               cockpit_device_id = devices.CMS,                                            value_down = 1.0,                                          value_up = 0.0, name = _('HOTAS CMS - Left (2x Flare + Chaff)'),           category = { _('Countermeasures') }, features = { 'Countermeasures' } },
        { combos = { { key = 'End', reformers = { 'RAlt' } } },    down = device_commands.CMSRight,               up = device_commands.CMSRight,              cockpit_device_id = devices.CMS,                                            value_down = 1.0,                                          value_up = 0.0, name = _('HOTAS CMS - Right (Abort Program)'),             category = { _('Countermeasures') }, features = { 'Countermeasures' } },
        { combos = { { key = 'PgDn', reformers = { 'RAlt' } } },   down = device_commands.CMSPress,               up = device_commands.CMSPress,              cockpit_device_id = devices.CMS,                                            value_down = 1.0,                                          value_up = 0.0, name = _('HOTAS CMS - Press (Reserved)'),                  category = { _('Countermeasures') }, features = { 'Countermeasures' } },
        { down = iCommandPlaneFire,                                 up = iCommandPlaneFireOff,                     name = _('Gun Fire - Direct (Fallback)'),   category = { _('Weapons') } },
        { combos = defaultDeviceAssignmentFor("weapon_release_button"), down = iCommandPlanePickleOn,             up = iCommandPlanePickleOff,                name = _('Weapon Release'),                                                  category = { _('Weapons') } },
        { combos = { { key = 'Space', reformers = { 'RAlt' } } },   down = iCommandPlanePickleOn,                 up = iCommandPlanePickleOff,                name = _('Weapon Release - Direct (Pickle Fallback)'),                       category = { _('Weapons') } },
        { down = iCommandPlaneLaunchPermissionOverride,             name = _('Launch Permission Override - Direct'),                             category = { _('Weapons') } },
        { down = iCommandPlaneDropSnarOnce,                         up = iCommandPlaneDropSnarOnceOff,            name = _('Countermeasures Release - Direct (Standard)'), category = { _('Countermeasures') }, features = { 'Countermeasures' } },
        { down = iCommandPlaneDropFlareOnce,                        name = _('Flare Release - Direct (Fallback)'), category = { _('Countermeasures') },        features = { 'Countermeasures' } },
        { down = iCommandPlaneDropChaffOnce,                        name = _('Chaff Release - Direct (Fallback)'), category = { _('Countermeasures') },        features = { 'Countermeasures' } },

        { combos = { { key = 'C', reformers = { 'RCtrl' } } },      down = 3007,                                   name = _('FBW CAT - Toggle'),               category = { _('Flight Control') } },
        { combos = { { key = '1', reformers = { 'RAlt' } } },       down = 3008,                                   name = _('FBW CAT - CAT I'),                category = { _('Flight Control') } },
        { combos = { { key = '3', reformers = { 'RAlt' } } },       down = 3009,                                   name = _('FBW CAT - CAT III'),              category = { _('Flight Control') } },
        { combos = { { key = 'G', reformers = { 'RCtrl' } } },      down = 3026,                                   up = 3026,                                  value_down = 1.0,                           value_up = 0.0, name = _('FBW G-Limiter Override (Hold)'),                 category = { _('Flight Control') } },
        { combos = { { key = 'G', reformers = { 'RAlt' } } },       down = 3027,                                   name = _('FBW G-Limiter Override (Toggle)'),category = { _('Flight Control') } },

        -- Autopilot
        { combos = { { key = 'A', reformers = { 'LAlt' } } },       down = device_commands.APMasterToggle,         up = device_commands.APMasterToggle,        cockpit_device_id = devices.AUTOPILOT,  value_down = 1.0, value_up = 0.0, name = _('AP Master - Toggle'),                    category = { _('Autopilot') } },
        { combos = { { key = 'A', reformers = { 'LAlt', 'LShift' } } }, down = device_commands.APMasterOff,        up = device_commands.APMasterOff,           cockpit_device_id = devices.AUTOPILOT,  value_down = 1.0, value_up = 0.0, name = _('AP Master - OFF'),                       category = { _('Autopilot') } },
        { combos = { { key = 'A', reformers = { 'LAlt', 'LCtrl' } } },  down = device_commands.APBypass,           up = device_commands.APBypass,              cockpit_device_id = devices.AUTOPILOT,  value_down = 1.0, value_up = 0.0, name = _('AP Bypass (Hold)'),                      category = { _('Autopilot') } },

        { combos = { { key = 'H', reformers = { 'LAlt' } } },       down = device_commands.APVertAltHold,          up = device_commands.APVertAltHold,         cockpit_device_id = devices.AUTOPILOT,  value_down = 1.0, value_up = 0.0, name = _('AP Vertical - ALT Hold'),                category = { _('Autopilot') } },
        { combos = { { key = 'H', reformers = { 'LCtrl' } } },      down = device_commands.APVertPitchHold,        up = device_commands.APVertPitchHold,       cockpit_device_id = devices.AUTOPILOT,  value_down = 1.0, value_up = 0.0, name = _('AP Vertical - Pitch Hold'),              category = { _('Autopilot') } },
        { combos = { { key = 'H', reformers = { 'LShift' } } },     down = device_commands.APVertVSHold,           up = device_commands.APVertVSHold,          cockpit_device_id = devices.AUTOPILOT,  value_down = 1.0, value_up = 0.0, name = _('AP Vertical - VS Hold'),                 category = { _('Autopilot') } },
        {                                                             down = device_commands.APVertIncrease,         up = device_commands.APVertIncrease,        cockpit_device_id = devices.AUTOPILOT,  value_down = 1.0, value_up = 0.0, name = _('AP Vertical Ref - Increase'),             category = { _('Autopilot') } },
        {                                                             down = device_commands.APVertDecrease,         up = device_commands.APVertDecrease,        cockpit_device_id = devices.AUTOPILOT,  value_down = 1.0, value_up = 0.0, name = _('AP Vertical Ref - Decrease'),             category = { _('Autopilot') } },

        { combos = { { key = 'J', reformers = { 'LAlt' } } },       down = device_commands.APLatHeadingHold,       up = device_commands.APLatHeadingHold,      cockpit_device_id = devices.AUTOPILOT,  value_down = 1.0, value_up = 0.0, name = _('AP Lateral - Heading Hold'),              category = { _('Autopilot') } },
        { combos = { { key = 'J', reformers = { 'LCtrl' } } },      down = device_commands.APLatHeadingSelect,     up = device_commands.APLatHeadingSelect,    cockpit_device_id = devices.AUTOPILOT,  value_down = 1.0, value_up = 0.0, name = _('AP Lateral - Heading Select'),            category = { _('Autopilot') } },
        { combos = { { key = 'J', reformers = { 'LShift' } } },     down = device_commands.APLatNavTrack,          up = device_commands.APLatNavTrack,         cockpit_device_id = devices.AUTOPILOT,  value_down = 1.0, value_up = 0.0, name = _('AP Lateral - NAV Track'),                category = { _('Autopilot') } },
        {                                                             down = device_commands.APLatIncrease,          up = device_commands.APLatIncrease,         cockpit_device_id = devices.AUTOPILOT,  value_down = 1.0, value_up = 0.0, name = _('AP Heading Ref - Increase'),              category = { _('Autopilot') } },
        {                                                             down = device_commands.APLatDecrease,          up = device_commands.APLatDecrease,         cockpit_device_id = devices.AUTOPILOT,  value_down = 1.0, value_up = 0.0, name = _('AP Heading Ref - Decrease'),              category = { _('Autopilot') } },

        { combos = { { key = 'T', reformers = { 'LAlt' } } },       down = device_commands.APAutoThrottleToggle,   up = device_commands.APAutoThrottleToggle,  cockpit_device_id = devices.AUTOPILOT,  value_down = 1.0, value_up = 0.0, name = _('AP Auto Throttle - Toggle'),              category = { _('Autopilot') } },
        {                                                             down = device_commands.APAutoThrottleOn,       up = device_commands.APAutoThrottleOn,      cockpit_device_id = devices.AUTOPILOT,  value_down = 1.0, value_up = 0.0, name = _('AP Auto Throttle - ON'),                  category = { _('Autopilot') } },
        {                                                             down = device_commands.APAutoThrottleOff,      up = device_commands.APAutoThrottleOff,     cockpit_device_id = devices.AUTOPILOT,  value_down = 1.0, value_up = 0.0, name = _('AP Auto Throttle - OFF'),                 category = { _('Autopilot') } },
        { combos = { { key = 'T', reformers = { 'LAlt', 'LCtrl' } } }, pressed = device_commands.APSpeedIncrease,  up = device_commands.APSpeedIncrease,       cockpit_device_id = devices.AUTOPILOT,  value_pressed = 1.0, value_up = 0.0, name = _('AP Speed Ref - Increase'),             category = { _('Autopilot') } },
        { combos = { { key = 'T', reformers = { 'LAlt', 'LShift' } } }, pressed = device_commands.APSpeedDecrease, up = device_commands.APSpeedDecrease,       cockpit_device_id = devices.AUTOPILOT,  value_pressed = 1.0, value_up = 0.0, name = _('AP Speed Ref - Decrease'),             category = { _('Autopilot') } },

        { combos = { { key = 'Y', reformers = { 'RAlt' } } },       down = device_commands.EngineThrustCutTestToggle, up = device_commands.EngineThrustCutTestToggle, cockpit_device_id = devices.AUTOPILOT, value_down = 1.0, value_up = 0.0, name = _('Engine Thrust Cut Test - Toggle'), category = { _('Flight Test') } },
        {                                                             down = device_commands.EngineThrustCutTestEnable, up = device_commands.EngineThrustCutTestEnable, cockpit_device_id = devices.AUTOPILOT, value_down = 1.0, value_up = 0.0, name = _('Engine Thrust Cut Test - Enable (Thrust = 0)'), category = { _('Flight Test') } },
        {                                                             down = device_commands.EngineThrustCutTestDisable, up = device_commands.EngineThrustCutTestDisable, cockpit_device_id = devices.AUTOPILOT, value_down = 1.0, value_up = 0.0, name = _('Engine Thrust Cut Test - Disable (Restore Thrust)'), category = { _('Flight Test') } },
    }
)

return res
