param(
    [Parameter(Mandatory = $true)]
    [string]$SystemsRoot,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Get-SystemEntryNames {
    param([string]$Root)

    if (-not (Test-Path -LiteralPath $Root -PathType Container)) {
        throw "System root does not exist: $Root"
    }

    $names = [System.Collections.Generic.List[string]]::new()
    foreach ($directory in Get-ChildItem -LiteralPath $Root -Directory) {
        $entry = Join-Path $directory.FullName "Entry.cpp"
        if (-not (Test-Path -LiteralPath $entry -PathType Leaf)) {
            continue
        }
        if ($directory.Name -notmatch '^[A-Za-z_][A-Za-z0-9_]*$') {
            throw "System directory is not a valid C++ identifier: $($directory.Name)"
        }
        $names.Add($directory.Name)
    }

    $result = $names.ToArray()
    [Array]::Sort($result, [StringComparer]::Ordinal)
    return $result
}

function New-CatalogContent {
    param([string[]]$EntryNames)

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("// Generated by tools/generate_system_catalog.ps1. Do not edit.")
    $lines.Add("// Generated system entries: $($EntryNames.Count)")
    $lines.Add('#include "Core/Systems/SystemPipeline.h"')
    $lines.Add("")
    $lines.Add("namespace Core")
    $lines.Add("{")
    $lines.Add("namespace Systems")
    $lines.Add("{")
    foreach ($name in $EntryNames) {
        $lines.Add("namespace Catalog { namespace $name { SystemEntry create_entry(); } }")
    }
    $lines.Add("")
    $lines.Add("std::vector<SystemEntry> load_generated_system_catalog()")
    $lines.Add("{")
    $lines.Add("`treturn {")
    foreach ($name in $EntryNames) {
        $lines.Add("`t`tCatalog::$name::create_entry(),")
    }
    $lines.Add("`t};")
    $lines.Add("}")
    $lines.Add("}")
    $lines.Add("}")
    return ($lines -join "`r`n") + "`r`n"
}

function Write-IfChanged {
    param(
        [string]$Path,
        [string]$Content
    )

    if ((Test-Path -LiteralPath $Path -PathType Leaf) -and
        [IO.File]::ReadAllText($Path) -ceq $Content) {
        return
    }

    $directory = Split-Path -Parent $Path
    [IO.Directory]::CreateDirectory($directory) | Out-Null
    $encoding = [Text.UTF8Encoding]::new($false)
    [IO.File]::WriteAllText($Path, $Content, $encoding)
}

$entries = @(Get-SystemEntryNames -Root $SystemsRoot)
$catalog = New-CatalogContent -EntryNames $entries
Write-IfChanged -Path $OutputPath -Content $catalog
