param(
    [string]$RepoRoot = (Split-Path -Parent $PSScriptRoot)
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$sourcePath = Join-Path $RepoRoot 'src\efm\F-CK-1C_EFM\DcsIds\CommandIds.json'
$cppPath = Join-Path $RepoRoot 'src\efm\F-CK-1C_EFM\DcsIds\CustomCommands.g.h'
$luaPath = Join-Path $RepoRoot 'Cockpit\Scripts\command_defs.lua'
$cockpitCppPath = Join-Path $RepoRoot 'src\efm\F-CK-1C_EFM\DcsIds\CockpitParams.g.h'
$cockpitLuaPath = Join-Path $RepoRoot 'Cockpit\Scripts\generated\CockpitParams.g.lua'

if (-not (Test-Path -LiteralPath $sourcePath)) {
    throw "Command ID source not found: $sourcePath"
}

$document = Get-Content -LiteralPath $sourcePath -Raw | ConvertFrom-Json
$seenNames = @{}
$commands = @($document.commands)
foreach ($command in $commands) {
    $name = [string]$command.name
    $value = [int]$command.value
    if ($name -notmatch '^[A-Za-z_][A-Za-z0-9_]*$') {
        throw "Invalid command name: $name"
    }
    if ($seenNames.ContainsKey($name)) {
        throw "Duplicate command name: $name"
    }
    if ($value -lt 3000 -or $value -gt 3999) {
        throw "Custom command ID outside reserved range 3000-3999: $name=$value"
    }
    $seenNames[$name] = $value
}

$seenParamNames = @{}
$cockpitParams = @($document.cockpit_params)
foreach ($param in $cockpitParams) {
    $name = [string]$param.name
    $value = [string]$param.value
    if ($name -notmatch '^[A-Za-z_][A-Za-z0-9_]*$') {
        throw "Invalid cockpit parameter name: $name"
    }
    if ($seenParamNames.ContainsKey($name)) {
        throw "Duplicate cockpit parameter name: $name"
    }
    if ([string]::IsNullOrWhiteSpace($value)) {
        throw "Empty cockpit parameter value: $name"
    }
    $seenParamNames[$name] = $value
}

$cpp = New-Object System.Collections.Generic.List[string]
$cpp.Add('#pragma once')
$cpp.Add('')
$cpp.Add('// Generated by tools/generate_dcs_ids.ps1 from DcsIds/CommandIds.json.')
$cpp.Add('// Do not edit this file directly.')
$cpp.Add('namespace DcsIds')
$cpp.Add('{')
$cpp.Add('namespace Commands')
$cpp.Add('{')
foreach ($command in $commands) {
    $cpp.Add(('static constexpr int {0} = {1};' -f $command.name, [int]$command.value))
}
$cpp.Add('}')
$cpp.Add('}')
$cpp.Add('')

$lua = New-Object System.Collections.Generic.List[string]
$lua.Add('-- Generated by tools/generate_dcs_ids.ps1 from DcsIds/CommandIds.json.')
$lua.Add('-- Do not edit this file directly.')
$lua.Add('device_commands = {')
foreach ($command in $commands) {
    $lua.Add(('    {0} = {1},' -f $command.name, [int]$command.value))
}
$lua.Add('}')
$lua.Add('')

$cockpitCpp = New-Object System.Collections.Generic.List[string]
$cockpitCpp.Add('#pragma once')
$cockpitCpp.Add('')
$cockpitCpp.Add('// Generated by tools/generate_dcs_ids.ps1 from DcsIds/CommandIds.json.')
$cockpitCpp.Add('// Do not edit this file directly.')
$cockpitCpp.Add('namespace DcsIds')
$cockpitCpp.Add('{')
$cockpitCpp.Add('namespace CockpitParams')
$cockpitCpp.Add('{')
foreach ($param in $cockpitParams) {
    $cockpitCpp.Add(('static const char* const {0} = "{1}";' -f $param.name, $param.value))
}
$cockpitCpp.Add('}')
$cockpitCpp.Add('}')
$cockpitCpp.Add('')

$cockpitLua = New-Object System.Collections.Generic.List[string]
$cockpitLua.Add('-- Generated by tools/generate_dcs_ids.ps1 from DcsIds/CommandIds.json.')
$cockpitLua.Add('-- Do not edit this file directly.')
$cockpitLua.Add('cockpit_params = {')
foreach ($param in $cockpitParams) {
    $cockpitLua.Add(('    {0} = "{1}",' -f $param.name, $param.value))
}
$cockpitLua.Add('}')
$cockpitLua.Add('')

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.Directory]::CreateDirectory((Split-Path -Parent $cppPath)) | Out-Null
[System.IO.Directory]::CreateDirectory((Split-Path -Parent $cockpitLuaPath)) | Out-Null
[System.IO.File]::WriteAllText($cppPath, ($cpp -join "`r`n"), $utf8NoBom)
[System.IO.File]::WriteAllText($luaPath, ($lua -join "`r`n"), $utf8NoBom)
[System.IO.File]::WriteAllText($cockpitCppPath, ($cockpitCpp -join "`r`n"), $utf8NoBom)
[System.IO.File]::WriteAllText($cockpitLuaPath, ($cockpitLua -join "`r`n"), $utf8NoBom)

$luaRoots = @(
    (Join-Path $RepoRoot 'Cockpit'),
    (Join-Path $RepoRoot 'Input')
)
foreach ($luaRoot in $luaRoots) {
    Get-ChildItem -LiteralPath $luaRoot -Filter '*.lua' -File -Recurse | ForEach-Object {
        $content = Get-Content -LiteralPath $_.FullName -Raw
        foreach ($match in [regex]::Matches($content, 'device_commands\.([A-Za-z_][A-Za-z0-9_]*)')) {
            $referencedName = $match.Groups[1].Value
            if (-not $seenNames.ContainsKey($referencedName)) {
                throw "Lua references unknown device command '$referencedName' in $($_.FullName)"
            }
        }
    }
}

Write-Output "Generated: $cppPath"
Write-Output "Generated: $luaPath"
Write-Output "Generated: $cockpitCppPath"
Write-Output "Generated: $cockpitLuaPath"
